backend:
  name: netlify-api
  url: http://localhost:8080

production:
  backend:
    name: github-api
    repo: owner/repo # Path to your Github repository
    branch: master # Branch to update (master by default)

media_folder: "assets/img/uploads" # Folder where user uploaded files should go
public_folder: "assets"

collections: # A list of collections the CMS should be able to edit
  - name: "news" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "News"  # Used in the UI, ie.: "New Post"
    folder: "news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Banner", name: "banner", widget: "image", class: "image featured"}
      - {label: "Short Description", name: "shortdesc", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Categories", name: "categories", widget: "string"}
  - name: "services" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Pages"  # Used in the UI, ie.: "New Post"
    files:
      - name: "serives"
        label: "Services"
        folder: "services" # The path to the folder where the documents are stored
        create: false # Allow users to create new documents in this collection
        fields: # The fields each document in this collection have
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Banner", name: "banner", widget: "image", class: "image featured"}
          - {label: "Short Description", name: "shortdesc", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          # meta: # Meta data fields. Just like fields, but without any preview element
          #   - {label: "Publish Date", name: "date", widget: "datetime"}
          #   - {label: "Categories", name: "categories", widget: "string"}
  - name: "slide"
    label: "Image Slider"
    files:
      - name: "slider"
        label: "Image Slide"
        file: "data/slider.json"
        fields:
          - label: "Image Slide"
            name: "slide"
            widget: "list"
            fields:
              - {label: "Image", name: "image", widget: "image", media_folder: "assets/img"}
              - {label: "Name", name: "name", widget: "string"}
      - name: "slidertext"
        label: "Slider Text"
        file: "data/slidertext.json"
        fields:
          - label: "Slider Text"
            name: "slide"
            widget: "list"
            fields:
              - {label: "Text", name: "text", widget: "string"}
              - {label: "Description", name: "description", widget: "string"}
